### ISSUE TITLE
Error in Python Program Line no #11

### ISSUE THREAD

**Issue by bipeensinha** [bipeensinha/mbbbatch2#1]
Hi All,

I found one bug in program @satyam14126  please look in =to this. and @kishorekamble  please carry on yiour feature development program.
![sandblaster](https://user-images.githubusercontent.com/49720823/145702982-6d1ad54a-7678-4633-b5fb-9fed45194700.png)

**Comment by satyam14126** [comment]
accepted.

**Comment by kishorekamble** [comment]
will look into this

**Comment by bipeensinha** [comment]
thank you , we arte done
![demo](https://user-images.githubusercontent.com/49720823/145703022-90f24ec5-898c-474a-8b1b-2ea5bb413f28.jpeg)
